import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/header";
import { communityLinks } from "@/lib/community";
import { canonical } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privasi",
  description:
    "Cara GDGoC IPB memakai dan menyimpan data dari login Google, form Apresiasi, dashboard member, dan papan skor Bogor Run, serta cara mengubah atau menghapusnya.",
  ...canonical("/privasi"),
};

export default function PrivacyPage() {
  return <><Header /><main id="main" className="privacy-page section-width"><p className="eyebrow">GDGOC IPB · APRESIASI & DASHBOARD</p><h1>Data untuk merayakan prestasi.</h1><p>Halaman ini menjelaskan penggunaan data saat kamu memakai form Apresiasi, dashboard member GDGoC IPB, dan papan skor Bogor Run.</p>
    <section><h2>Akun dan isian form</h2><p>Login Google memberikan informasi profil dasar, termasuk nama, email, dan foto profil jika tersedia. Nama dan email dipakai untuk mengenali pemilik draft dan kiriman. Form meminta informasi prestasi, identitas yang akan dicantumkan, akun Instagram, cerita, dan link dokumentasi.</p></section>
    <section><h2>Perkenalan pertama</h2><p>Onboarding meminta nama yang ingin dipakai, kampus, program studi, serta peranmu sebagai Member atau Core Team beserta divisinya. Admin juga bisa menandai pengurus sebagai BoD (Board of Directors), dengan atau tanpa divisi; tanda ini tersimpan di profil dan tampil untuk admin serta di profilmu sendiri. Profil serta langkah yang sudah diselesaikan disimpan di akunmu agar perkenalan bisa dilanjutkan dan tidak muncul lagi setelah selesai. Data ini mengisi awal draft apresiasi baru dan tetap bisa dikoreksi pada form sebelum dikirim.</p><p>Ajakan bergabung ke WhatsApp dan Google Developer Groups bersifat opsional. Link membuka layanan terkait di tab baru; membuka link tidak otomatis membuatmu bergabung. Website tidak mengambil daftar anggota grup atau mencatat status keanggotaanmu di kedua layanan tersebut.</p></section>
    <section><h2>Siapa yang bisa melihat?</h2><p>Draft hanya bisa diakses pemilik akun melalui aplikasi. Setelah dikirim, informasi tersedia bagi tim peninjau yang menyiapkan apresiasi: pemilik dan admin GDGoC IPB, anggota yang ditunjuk pemilik sebagai peninjau, serta Core Team dan BoD divisi Media & Creative yang perannya sudah dikonfirmasi pengurus. Pengelola teknis memiliki akses ke penyimpanan layanan untuk menjalankan aplikasi. Kiriman apresiasi tidak ditampilkan sebagai daftar publik di website.</p></section>
    <section><h2>Dashboard dan tugas</h2><p>Dashboard memakai akun Google dan profil perkenalan yang sama. Saat mengumpulkan tugas, jawaban tertulis dan file yang kamu unggah disimpan bersama waktu pengiriman. Kiriman hanya bisa dilihat olehmu dan admin GDGoC IPB, termasuk nama, email, dan kampus pada profilmu. Admin juga bisa menunjuk penilai untuk satu tugas, misalnya mentor program; penilai melihat jawaban, file, nama, kampus, dan nilai pada tugas itu saja, tanpa email.</p><p>Gambar PNG, JPG, dan WebP dikecilkan dan diubah ke WebP di perangkatmu sebelum diunggah, sehingga metadata seperti lokasi GPS ikut terhapus. Link file dibuat acak dan hanya diberikan kepada pemilik kiriman dan admin. Siapa pun yang memegang link tersebut dapat membuka filenya, jadi jangan membagikannya dan hindari mengunggah data sensitif yang tidak diperlukan. File yang diunggah tetapi tidak jadi dikirim dihapus otomatis setelah sekitar 24 jam; file yang kamu ganti saat mengirim ulang langsung dihapus.</p><p>Admin dapat menonaktifkan akses dashboard sebuah akun. Kiriman yang sudah ada tetap tersimpan dan dapat dibuka kembali setelah akun diaktifkan. Selama nonaktif, skor Bogor Run akun itu juga disembunyikan dari papan skor.</p></section>
    <section><h2>Bogor Run dan papan skor</h2><p>Bogor Run, game Dino di bagian bawah beranda, bisa dimainkan tanpa login. Rekor pribadimu, pilihan suara (nyala atau bisu), dan pilihan tampilan dino hanya disimpan di localStorage browser ini dan tidak dikirim ke server. Saat game tampil di layar, browser meminta tiket permainan dari server tanpa login; tiket itu tidak disimpan di server.</p><p>Jika kamu sedang login dengan Google, permainan yang selesai, karena menabrak atau karena bertahan satu jam penuh, otomatis dikirim ke papan skor: tiket permainan dari server, catatan kapan kamu melompat, menunduk, dan berdiri, panjang permainan, serta skornya. Server memainkan ulang catatan itu untuk memastikan skornya cocok, lalu tidak menyimpan catatan tombol tersebut. Untuk setiap permainan yang diterima, server menyimpan bersama akunmu skor, nomor acak (seed), panjang permainan, waktu tiket diterbitkan (kira-kira saat kamu mulai bermain), waktu penyimpanan, dan minggu permainannya. Catatan per permainan ini dihapus otomatis 30 hari setelah disimpan. Yang disimpan lebih lama adalah skor terbaikmu tiap minggu dan sepanjang masa, beserta nama pendek dan waktu skor itu dicapai, serta jumlah pemain dan permainan per periode.</p><p>Papan skor di beranda bisa dilihat siapa pun, termasuk pengunjung yang belum login. Isinya hanya peringkat, nama pendek, dan skor. Nama pendek diambil dari profil perkenalan atau akun Google, berupa nama depan dan inisial nama belakang (misalnya “Aldio L.”). Nama yang hanya terdiri dari satu kata ditampilkan utuh, karena tidak ada nama belakang untuk disingkat. Di dashboard, member juga melihat 100 besar beserta waktu skor dicapai, jumlah pemain, dan jumlah permainan tercatat. Email dan foto tidak pernah ditampilkan.</p><p>Pemilik dan admin GDGoC IPB dapat menyembunyikan pemain dari semua papan skor, termasuk skor yang dicapai sesudahnya; skornya tetap tersimpan. Admin hanya dapat menyembunyikan member, dan pemain yang disembunyikan pemilik hanya bisa ditampilkan lagi oleh pemilik. Kami mencatat siapa yang terakhir menyembunyikan dan menampilkan kembali seorang pemain, beserta waktunya. Pemilik dan admin melihat daftar pemain yang disembunyikan, termasuk siapa yang menyembunyikannya dan kapan. Jika akunmu dinonaktifkan, skormu ikut disembunyikan dan tampil lagi setelah akunmu diaktifkan kembali, kecuali pemilik atau admin juga menyembunyikannya secara terpisah.</p><p>Jika kamu belum login saat permainan selesai lalu memilih “Masuk untuk simpan skor”, data permainan tadi disimpan sementara di sessionStorage tab tersebut agar bisa dikirim setelah login Google. Data itu dihapus begitu dibaca, diabaikan jika permainan sudah selesai lebih dari 30 menit, dan hilang saat tab ditutup.</p></section>
    <section><h2>Materi untuk Instagram</h2><p>Dengan memberikan persetujuan saat mengirim form, kamu mengizinkan penggunaan nama, akun Instagram, cerita, dan dokumentasi untuk materi apresiasi GDGoC IPB. Email login tidak termasuk materi publikasi. Tim meninjau kiriman sebelum menyiapkan collab post; mengirim form tidak menjamin waktu publikasi.</p></section>
    <section><h2>Penyimpanan dan layanan</h2><p>Akun, sesi, draft, kiriman, file tugas, dan skor Bogor Run disimpan menggunakan Convex. Website dihosting di Vercel dan login diproses melalui Google. Browser memakai cookie sesi untuk login serta cadangan lokal per akun untuk memulihkan perubahan draft yang belum tersinkron. Cadangan lokal dihapus setelah perubahan berhasil tersimpan ke akun.</p><p>Link dokumentasi tetap berada di layanan asal, misalnya Google Drive. Atur akses link agar materi yang dibagikan sesuai kebutuhan dan hindari memasukkan data sensitif yang tidak diperlukan.</p></section>
    <section><h2>Mengubah atau menghapus data</h2><p>Kamu bisa mengubah dan menghapus draft yang belum dikirim dari halaman Apresiasi, serta mengganti jawaban dan file tugas selama pengumpulan masih dibuka. Untuk koreksi kiriman, penghapusan kiriman tugas, penarikan persetujuan publikasi, atau permintaan penghapusan data akun, kiriman, dan skor Bogor Run, hubungi <a href={communityLinks.instagram} target="_blank" rel="noreferrer">@gdgoc.ipb</a> dengan menyebutkan email akun dan prestasi yang dimaksud.</p><p>Jika kamu meminta akunmu dihapus, pemilik GDGoC IPB menghapusnya dari dashboard: profil, draft dan kiriman apresiasi beserta riwayat tinjauannya, kiriman tugas beserta file dan nilainya, skor Bogor Run, penunjukan sebagai penilai, serta akun login dan sesinya. Catatan milik orang lain yang menyebut akunmu, misalnya siapa yang menilai sebuah tugas, tetap ada tetapi tidak lagi menampilkan namamu. Kami hanya menyimpan catatan bahwa sebuah akun dihapus, oleh siapa, kapan, dan berapa banyak data yang terhapus, tanpa nama atau email. Materi yang sudah terbit di Instagram dikelola terpisah melalui permintaan penarikan persetujuan.</p><p>Setiap perubahan akses di dashboard dicatat untuk pemilik GDGoC IPB: menjadikan atau menurunkan admin, memberi atau mencabut akses peninjau apresiasi, menonaktifkan atau mengaktifkan akun, mengubah peran komunitas, menunjuk penilai tugas, dan menghapus akun. Catatan berisi siapa yang mengubah, untuk akun siapa, kapan, serta nilai sebelum dan sesudahnya, dan hanya bisa dilihat pemilik. Catatan menyimpan ID akun, bukan nama atau email; setelah akun dihapus, catatannya tetap ada tanpa nama.</p></section>
    <Link className="button button-blue" href="/dashboard">Ke dashboard</Link>
  </main></>;
}
