import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/header";
import { communityLinks } from "@/lib/community";

export const metadata: Metadata = { title: "Privasi" };

export default function PrivacyPage() {
  return <><Header /><main id="main" className="privacy-page section-width"><p className="eyebrow">GDGOC IPB · APRESIASI & DASHBOARD</p><h1>Data untuk merayakan prestasi.</h1><p>Halaman ini menjelaskan penggunaan data saat kamu memakai form Apresiasi dan dashboard member GDGoC IPB.</p>
    <section><h2>Akun dan isian form</h2><p>Login Google memberikan informasi profil dasar, termasuk nama, email, dan foto profil jika tersedia. Nama dan email dipakai untuk mengenali pemilik draft dan kiriman. Form meminta informasi prestasi, identitas yang akan dicantumkan, akun Instagram, cerita, dan link dokumentasi.</p></section>
    <section><h2>Perkenalan pertama</h2><p>Onboarding meminta nama yang ingin dipakai, kampus, program studi, serta peranmu sebagai Member atau Core Team beserta divisinya. Profil serta langkah yang sudah diselesaikan disimpan di akunmu agar perkenalan bisa dilanjutkan dan tidak muncul lagi setelah selesai. Data ini mengisi awal draft apresiasi baru dan tetap bisa dikoreksi pada form sebelum dikirim.</p><p>Ajakan bergabung ke WhatsApp dan Google Developer Groups bersifat opsional. Link membuka layanan terkait di tab baru; membuka link tidak otomatis membuatmu bergabung. Website tidak mengambil daftar anggota grup atau mencatat status keanggotaanmu di kedua layanan tersebut.</p></section>
    <section><h2>Siapa yang bisa melihat?</h2><p>Draft hanya bisa diakses pemilik akun melalui aplikasi. Setelah dikirim, informasi tersedia bagi admin yang ditunjuk untuk meninjau dan menyiapkan apresiasi. Pengelola teknis memiliki akses ke penyimpanan layanan untuk menjalankan aplikasi. Data tidak ditampilkan sebagai daftar publik di website.</p></section>
    <section><h2>Dashboard dan tugas</h2><p>Dashboard memakai akun Google dan profil perkenalan yang sama. Saat mengumpulkan tugas, jawaban tertulis dan file yang kamu unggah disimpan bersama waktu pengiriman. Kiriman hanya bisa dilihat olehmu dan admin GDGoC IPB, termasuk nama, email, dan kampus pada profilmu.</p><p>Gambar PNG, JPG, dan WebP dikecilkan dan diubah ke WebP di perangkatmu sebelum diunggah, sehingga metadata seperti lokasi GPS ikut terhapus. Link file dibuat acak dan hanya diberikan kepada pemilik kiriman dan admin. Siapa pun yang memegang link tersebut dapat membuka filenya, jadi jangan membagikannya dan hindari mengunggah data sensitif yang tidak diperlukan. File yang diunggah tetapi tidak jadi dikirim dihapus otomatis setelah sekitar 24 jam; file yang kamu ganti saat mengirim ulang langsung dihapus.</p><p>Admin dapat menonaktifkan akses dashboard sebuah akun. Kiriman yang sudah ada tetap tersimpan dan dapat dibuka kembali setelah akun diaktifkan.</p></section>
    <section><h2>Materi untuk Instagram</h2><p>Dengan memberikan persetujuan saat mengirim form, kamu mengizinkan penggunaan nama, akun Instagram, cerita, dan dokumentasi untuk materi apresiasi GDGoC IPB. Email login tidak termasuk materi publikasi. Tim meninjau kiriman sebelum menyiapkan collab post; mengirim form tidak menjamin waktu publikasi.</p></section>
    <section><h2>Penyimpanan dan layanan</h2><p>Akun, sesi, draft, kiriman, dan file tugas disimpan menggunakan Convex. Website dihosting di Vercel dan login diproses melalui Google. Browser memakai cookie sesi untuk login serta cadangan lokal per akun untuk memulihkan perubahan draft yang belum tersinkron. Cadangan lokal dihapus setelah perubahan berhasil tersimpan ke akun.</p><p>Link dokumentasi tetap berada di layanan asal, misalnya Google Drive. Atur akses link agar materi yang dibagikan sesuai kebutuhan dan hindari memasukkan data sensitif yang tidak diperlukan.</p></section>
    <section><h2>Mengubah atau menghapus data</h2><p>Kamu bisa mengubah dan menghapus draft yang belum dikirim dari halaman Apresiasi, serta mengganti jawaban dan file tugas selama pengumpulan masih dibuka. Untuk koreksi kiriman, penghapusan kiriman tugas, penarikan persetujuan publikasi, atau permintaan penghapusan data akun dan kiriman, hubungi <a href={communityLinks.instagram} target="_blank" rel="noreferrer">@gdgoc.ipb</a> dengan menyebutkan email akun dan prestasi yang dimaksud.</p></section>
    <Link className="button button-blue" href="/dashboard">Ke dashboard</Link>
  </main></>;
}
