// Renders public/brand/og-image.jpg, the 1200 × 630 preview shown when a link is shared (see src/lib/site.ts).
// The background is a still of the landing's Three.js campus, captured from /environment in headless Chrome.
//
// Start the site (`pnpm dev` or `pnpm start`), then run from the repository root after changing the scene,
// the lockup, or the copy:
//   node design/og-image.mjs [site URL, default http://127.0.0.1:3104]
// Set CHROME_PATH if Chrome is not in /Applications.
//
// The image is committed as a JPEG instead of being generated by an `opengraph-image.tsx` route: the scene
// needs WebGL, and `next/og` only emits PNG, which is over 1 MB for this artwork; chat apps skip heavy previews.
import { spawn } from "node:child_process";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { setTimeout as sleep } from "node:timers/promises";
import { ImageResponse } from "next/og.js";
import sharp from "sharp";

const site = (process.argv[2] ?? "http://127.0.0.1:3104").replace(/\/+$/, "");
const chromePath = process.env.CHROME_PATH ?? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const size = { width: 1200, height: 630 };
const paper = "#faf9f2";
const ink = "#172d43";
const blue = "#2464e8";

/** A PNG of the campus scene alone, in the deterministic `?motion=off` pose, at twice the output size. */
async function captureScene() {
  const profile = await mkdtemp(join(tmpdir(), "og-image-chrome-"));
  const chrome = spawn(chromePath, ["--headless=new", "--remote-debugging-port=0", `--user-data-dir=${profile}`, "--no-first-run", "--hide-scrollbars", "about:blank"], { stdio: ["ignore", "ignore", "pipe"] });
  try {
    const devtools = await new Promise((resolve, reject) => {
      let log = "";
      chrome.stderr.on("data", (chunk) => {
        log += chunk;
        const match = log.match(/DevTools listening on (ws:\S+)/);
        if (match) resolve(new URL(match[1]));
      });
      chrome.once("error", reject);
      chrome.once("exit", () => reject(new Error(`Chrome exited before DevTools was ready:\n${log}`)));
    });
    const tab = await (await fetch(`http://${devtools.host}/json/new?about:blank`, { method: "PUT" })).json();
    const socket = new WebSocket(tab.webSocketDebuggerUrl);
    await new Promise((resolve, reject) => {
      socket.onopen = resolve;
      socket.onerror = () => reject(new Error("Could not connect to Chrome DevTools"));
    });
    const pending = new Map();
    socket.onmessage = ({ data }) => {
      const { id, result, error } = JSON.parse(data);
      const call = pending.get(id);
      if (!call) return;
      pending.delete(id);
      if (error) call.reject(new Error(error.message));
      else call.resolve(result);
    };
    let calls = 0;
    const send = (method, params = {}) =>
      new Promise((resolve, reject) => {
        pending.set(++calls, { resolve, reject });
        socket.send(JSON.stringify({ id: calls, method, params }));
      });
    const evaluate = async (expression) => (await send("Runtime.evaluate", { expression, returnByValue: true })).result.value;

    await send("Emulation.setDeviceMetricsOverride", { ...size, deviceScaleFactor: 2, mobile: false });
    await send("Page.navigate", { url: `${site}/environment?motion=off` });
    // `data-ready` is only set by a rendered WebGL frame, never by the static image fallback.
    for (let attempt = 0; !(await evaluate(`document.querySelector(".campus-environment")?.dataset.ready === "true"`)); attempt++) {
      if (attempt === 100) throw new Error(`The 3D scene did not render at ${site}/environment. Is the site running, and does this Chrome have WebGL?`);
      await sleep(200);
    }
    await evaluate(`document.querySelector(".environment-toolbar").style.display = "none"`);
    await sleep(500);
    const { data } = await send("Page.captureScreenshot", { format: "png" });
    socket.close();
    return Buffer.from(data, "base64");
  } finally {
    chrome.kill();
    await rm(profile, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
  }
}

const font = (weight) => readFile(`node_modules/@fontsource/poppins/files/poppins-latin-${weight}-normal.woff`);
const h = (type, style, children, props) => ({ type, props: { ...props, style, children } });

const scene = await captureScene();
const logo = `data:image/svg+xml;base64,${await readFile("public/brand/gdgoc-ipb.svg", "base64")}`;

const image = new ImageResponse(
  h("div", { width: "100%", height: "100%", display: "flex", position: "relative", background: paper, color: ink, fontFamily: "Poppins" }, [
    h("img", { position: "absolute", left: 0, top: 0 }, undefined, { src: `data:image/png;base64,${scene.toString("base64")}`, ...size }),
    // A paper wash behind the copy, fading out before the Dino and AHN.
    h("div", { position: "absolute", left: 0, top: 0, ...size, display: "flex", backgroundImage: `radial-gradient(640px 280px at 300px 120px, ${paper} 0%, ${paper} 62%, #faf9f200 100%)` }),
    h("div", { position: "absolute", left: 64, top: 48, display: "flex", flexDirection: "column", alignItems: "flex-start" }, [
      h("img", {}, undefined, { src: logo, width: 330, height: 44 }),
      h("div", { display: "flex", flexDirection: "column", marginTop: 30, fontSize: 58, fontWeight: 700, lineHeight: 1.1, letterSpacing: "-0.03em" }, [
        h("span", {}, "Belajar teknologi"),
        h("span", { color: blue }, "bareng GDGoC IPB"),
      ]),
      h("div", { marginTop: 18, fontSize: 22, fontWeight: 500 }, "Komunitas mahasiswa Bogor · coding, UI/UX, AI"),
    ]),
  ]),
  {
    ...size,
    fonts: [
      { name: "Poppins", data: await font(500), weight: 500, style: "normal" },
      { name: "Poppins", data: await font(700), weight: 700, style: "normal" },
    ],
  },
);

const jpeg = await sharp(Buffer.from(await image.arrayBuffer())).jpeg({ quality: 84, mozjpeg: true }).toBuffer();
await writeFile("public/brand/og-image.jpg", jpeg);
console.log(`public/brand/og-image.jpg: ${Math.round(jpeg.length / 1024)} KB`);
