// Renders public/brand/og-image.jpg, the 1200 × 630 preview shown when a link is shared (see src/lib/site.ts).
// The background is a still of the landing's Three.js campus, captured from /environment in headless Chrome.
//
// Start the site (`pnpm dev` or `pnpm start`), then run from the repository root after changing the scene,
// the lockup, or the copy:
//   node design/og-image.mjs [site URL, default http://127.0.0.1:3104]
//
// The image is committed as a JPEG instead of being generated by an `opengraph-image.tsx` route: the scene
// needs WebGL, and `next/og` only emits PNG, which is over 1 MB for this artwork; chat apps skip heavy previews.
import { readFile, writeFile } from "node:fs/promises";
import { ImageResponse } from "next/og.js";
import sharp from "sharp";
import { captureScene } from "./campus-still.mjs";

const size = { width: 1200, height: 630 };
const paper = "#faf9f2";
const ink = "#172d43";
const blue = "#2464e8";

const font = (weight) => readFile(`node_modules/@fontsource/poppins/files/poppins-latin-${weight}-normal.woff`);
const h = (type, style, children, props) => ({ type, props: { ...props, style, children } });

const scene = await captureScene({ ...size, deviceScaleFactor: 2 });
const logo = `data:image/svg+xml;base64,${await readFile("public/brand/gdgoc-ipb.svg", "base64")}`;

const image = new ImageResponse(
  h("div", { width: "100%", height: "100%", display: "flex", position: "relative", background: paper, color: ink, fontFamily: "Poppins" }, [
    h("img", { position: "absolute", left: 0, top: 0 }, undefined, { src: `data:image/png;base64,${scene.toString("base64")}`, ...size }),
    // A paper wash behind the copy, fading out before the Dino and AHN.
    h("div", { position: "absolute", left: 0, top: 0, ...size, display: "flex", backgroundImage: `radial-gradient(640px 280px at 300px 120px, ${paper} 0%, ${paper} 62%, #faf9f200 100%)` }),
    h("div", { position: "absolute", left: 64, top: 48, display: "flex", flexDirection: "column", alignItems: "flex-start" }, [
      h("img", {}, undefined, { src: logo, width: 330, height: 44 }),
      h("div", { display: "flex", flexDirection: "column", marginTop: 30, fontSize: 58, fontWeight: 700, lineHeight: 1.1, letterSpacing: "-0.03em" }, [
        h("span", {}, "Belajar teknologi"),
        h("span", { color: blue }, "bareng GDGoC IPB"),
      ]),
      h("div", { marginTop: 18, fontSize: 22, fontWeight: 500 }, "Komunitas mahasiswa Bogor · coding, UI/UX, AI"),
    ]),
  ]),
  {
    ...size,
    fonts: [
      { name: "Poppins", data: await font(500), weight: 500, style: "normal" },
      { name: "Poppins", data: await font(700), weight: 700, style: "normal" },
    ],
  },
);

const jpeg = await sharp(Buffer.from(await image.arrayBuffer())).jpeg({ quality: 84, mozjpeg: true }).toBuffer();
await writeFile("public/brand/og-image.jpg", jpeg);
console.log(`public/brand/og-image.jpg: ${Math.round(jpeg.length / 1024)} KB`);
